// // client/src/pages/HomePage.jsx
// import React from 'react';
// import { Link } from 'react-router-dom';
// import { FaLaptopCode, FaBrain, FaChartLine } from 'react-icons/fa';

// const HomePage = () => {
//     return (
//         <div className="min-h-[calc(100vh-8rem)] flex flex-col justify-center items-center text-center p-6 bg-gradient-to-br from-blue-50 to-indigo-100">
//             <h1 className="text-5xl md:text-6xl font-extrabold text-gray-900 mb-4 animate-fadeIn">
//                 <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">AI Powered</span> Meal Planner
//             </h1>
//             <p className="text-xl text-gray-600 mb-10 max-w-3xl animate-fadeIn delay-100">
//                 Generate a custom meal plan tailored to your body metrics, dietary preferences, and fitness goals using the power of AI.
//             </p>
//             <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-6">
//                 <Link to="/profile" className="btn btn-primary text-lg px-8 py-4 animate-bounceIn">
//                     Get Started Now
//                 </Link>
//                 <Link to="/login" className="btn bg-gray-300 text-gray-800 hover:bg-gray-400 text-lg px-8 py-4 animate-bounceIn delay-100">
//                     Already a user? Log In
//                 </Link>
//             </div>
            
//             <div className="mt-20 w-full max-w-4xl grid grid-cols-1 md:grid-cols-3 gap-8">
//                 <div className="p-8 bg-white rounded-2xl shadow-lg flex flex-col items-center text-center transform hover:scale-105 transition-transform duration-300">
//                     <FaBrain className="text-5xl text-blue-500 mb-4" />
//                     <h3 className="text-xl font-bold mb-2">AI Personalization</h3>
//                     <p className="text-gray-600">Get meal plans generated by AI based on your unique data.</p>
//                 </div>
//                 <div className="p-8 bg-white rounded-2xl shadow-lg flex flex-col items-center text-center transform hover:scale-105 transition-transform duration-300">
//                     <FaChartLine className="text-5xl text-green-500 mb-4" />
//                     <h3 className="text-xl font-bold mb-2">Track Your Progress</h3>
//                     <p className="text-gray-600">Monitor your fitness goals with a data-driven approach.</p>
//                 </div>
//                 <div className="p-8 bg-white rounded-2xl shadow-lg flex flex-col items-center text-center transform hover:scale-105 transition-transform duration-300">
//                     <FaLaptopCode className="text-5xl text-purple-500 mb-4" />
//                     <h3 className="text-xl font-bold mb-2">Beautiful Interface</h3>
//                     <p className="text-gray-600">Enjoy a clean, modern, and user-friendly experience.</p>
//                 </div>
//             </div>
//         </div>
//     );
// };

// export default HomePage;






import React from 'react';
import { Link } from 'react-router-dom';
import { FaLaptopCode, FaBrain, FaChartLine } from 'react-icons/fa';

const HomePage = () => {
    return (
        <div className="min-h-screen flex flex-col justify-center items-center text-center px-6 py-12 bg-gradient-to-br from-white via-blue-50 to-indigo-100">
            {/* Hero Section */}
            <div className="max-w-5xl w-full">
                <h1 className="text-4xl md:text-6xl font-extrabold text-gray-900 mb-6 leading-tight">
                    <span className="bg-clip-text text-transparent bg-gradient-to-r from-emerald-500 to-teal-600">
                        AI-Powered
                    </span>{' '}
                    Meal Planner
                </h1>
                <p className="text-lg md:text-xl text-gray-600 mb-10 max-w-3xl mx-auto">
                    Personalized meal plans based on your body, preferences, and goals. Backed by smart AI to make your fitness journey simple and delicious.
                </p>

                <div className="flex flex-col md:flex-row justify-center items-center gap-4 md:gap-6">
                    <Link
                        to="/login"
                        className="px-8 py-3 text-lg font-semibold bg-emerald-600 text-white rounded-lg shadow-md hover:bg-emerald-700 transition"
                    >
                        Get Started
                    </Link>
                    <Link
                        to="/login"
                        className="px-8 py-3 text-lg font-semibold bg-white text-gray-700 border border-gray-300 rounded-lg shadow hover:bg-gray-100 transition"
                    >
                        Already a user? Log In
                    </Link>
                </div>
            </div>

            {/* Feature Cards */}
            <div className="mt-20 w-full max-w-5xl grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="bg-white p-8 rounded-2xl shadow-md hover:shadow-lg transition transform hover:-translate-y-1">
                    <FaBrain className="text-5xl text-emerald-500 mb-4 mx-auto" />
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">AI Personalization</h3>
                    <p className="text-gray-600 text-sm">
                        Smart recommendations based on your lifestyle, body type, and goals.
                    </p>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-md hover:shadow-lg transition transform hover:-translate-y-1">
                    <FaChartLine className="text-5xl text-indigo-500 mb-4 mx-auto" />
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">Track Progress</h3>
                    <p className="text-gray-600 text-sm">
                        Keep an eye on your nutritional intake and physical progress over time.
                    </p>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-md hover:shadow-lg transition transform hover:-translate-y-1">
                    <FaLaptopCode className="text-5xl text-purple-500 mb-4 mx-auto" />
                    <h3 className="text-xl font-semibold text-gray-800 mb-2">Smooth Interface</h3>
                    <p className="text-gray-600 text-sm">
                        Enjoy a simple, clean UI designed for ease and beauty across all devices.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default HomePage;
